name: Set up .NET and other dependencies
description: Select the .NET version, Xcode, and JDK to be used to compile the SDK

runs:
  using: "composite"
  steps:

    - name: Select JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '21'

    - name: Select .NET
      uses: actions/setup-dotnet@v5
      id: dotnet
      with:
        dotnet-version: '9.x.x'

    # As per https://github.com/actions/setup-dotnet/issues/679#issuecomment-3536292429
    - name: Create `global.json`
      shell: bash
      run: |
        echo '{"sdk":{"version": "${{ steps.dotnet.outputs.dotnet-version }}"}}' > ./global.json

    - name: Select Xcode version
      env:
        XCODE_SELECTED_PATH: "/Applications/Xcode_16.2.app"
      shell: bash
      run: sudo xcode-select --switch ${XCODE_SELECTED_PATH}

    - name: Print toolchain versions
      shell: bash
      run: |
        dotnet --version
        xcodebuild -version
        java -version
