name: Set up .NET and other dependencies
description: Select the .NET version, Xcode, and JDK to be used to compile the SDK

runs:
  using: "composite"
  steps:

    - name: Select JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Select .NET
      uses: actions/setup-dotnet@v5
      id: dotnet
      with:
        dotnet-version: '10.x.x'

    # As per https://github.com/actions/setup-dotnet/issues/679#issuecomment-3536292429
    - name: Create `global.json`
      shell: bash
      run: |
        echo '{"sdk":{"version": "${{ steps.dotnet.outputs.dotnet-version }}"}}' > ./global.json

    - name: Select Xcode version
      env:
        XCODE_SELECTED_PATH: "/Applications/Xcode_26.0.1.app"
      shell: bash
      run: |
        sudo xcode-select --switch ${XCODE_SELECTED_PATH}

    # `xcodebuild -downloadPlatform` may fail due to simulator misconfiguration:
    # https://github.com/actions/runner-images/issues/12758
    - name: Download the iOS runtime
      shell: bash
      run: |
        xcrun simctl list > /dev/null
        xcrun xcodebuild -downloadPlatform iOS

    - name: Warm up Xcode
      shell: bash
      run: |
        xcode-select -p
        xcodebuild -version
        sudo xcodebuild -runFirstLaunch
        sudo xcodebuild -license accept

    - name: Print toolchain versions
      shell: bash
      run: |
        dotnet --version
        xcodebuild -version
        java -version

    - name: Install dotnet-script
      shell: bash
      run: |
        dotnet tool install -g dotnet-script
        dotnet script UpdateSDKs/UpdateSDKs.csx -- help

    # 10.0.100 is the first version of the .NET 10 workloads that supports Xcode 26.
    # https://github.com/dotnet/macios/releases/tag/dotnet-10.0.1xx-xcode26.0-11017.0
    - name: Install .NET workloads
      shell: bash
      run: |
        dotnet workload install maui ios android --version 10.0.100
        dotnet workload list
