name: Build and pack a NuGet package

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Cake build script
      run: |
        ./build.sh --verbosity diagnostic
