name: Build, pack NuGet packages, publish to NuGet.org

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: macos-15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x.x'

    - name: Select Xcode version
      env:
        XCODE_SELECTED_PATH: "/Applications/Xcode_16.2.app"
      shell: bash
      run: sudo xcode-select --switch ${XCODE_SELECTED_PATH}

    - name: Print toolchain versions
      run: |
        dotnet --version
        xcodebuild -version
        java -version

    - name: Install .NET workloads
      run: |
        sudo dotnet workload restore

    - name: Restore NuGet packages
      run: |
        dotnet restore CobrowseIO.sln

    - name: Build SDK projects
      run: |
        dotnet build Android/NumbersJava.Android/NumbersJava.Android.csproj --configuration "Release" --no-dependencies --no-restore
        dotnet build Android/CborJava.Android/CborJava.Android.csproj --configuration "Release" --no-dependencies --no-restore
        dotnet build Android/CobrowseIO.Android/CobrowseIO.Android.csproj --configuration "Release" --no-dependencies --no-restore
        dotnet build iOS/CobrowseIO.iOS/CobrowseIO.iOS.csproj --configuration "Release" --no-dependencies --no-restore
        dotnet build SDK/CobrowseIO/CobrowseIO.csproj --configuration "Release" --no-dependencies --no-restore

    - name: Create NuGet packages
      run: |
        dotnet pack SDK/CobrowseIO/CobrowseIO.csproj /p:NuspecFile=../../CobrowseIO.DotNet.nuspec --no-build

    - name: Copy nupkg files to artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          SDK/CobrowseIO/bin/Release/CobrowseIO.DotNet.*.nupkg
        retention-days: 7
        if-no-files-found: error

    - name: Push nupkg files to NuGet.org
      run: |
        dotnet nuget push SDK/CobrowseIO/bin/Release/CobrowseIO.DotNet.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_PUSH_TOKEN }} --skip-duplicate
