name: Update native SDKs and commit the changes

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'SDK platform (Android or iOS)'
        default: ''
        type: string
        required: true
      cobrowse_sdk_version:
        description: 'Native SDK version'
        default: ''
        type: string
        required: false

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: job-update-packages
  cancel-in-progress: false

jobs:
  update-native-sdk:
    runs-on: macos-15
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x.x'

    - name: Select Xcode version
      env:
        XCODE_SELECTED_PATH: "/Applications/Xcode_16.2.app"
      shell: bash
      run: sudo xcode-select --switch ${XCODE_SELECTED_PATH}

    - name: Print toolchain versions
      run: |
        dotnet --version
        xcodebuild -version
        java -version

    - name: Install .NET script
      run: |
        dotnet tool install -g dotnet-script
        
    - name: Update native SDK
      run: |
        git submodule update --init --recursive
        git submodule foreach --recursive 'git fetch --tags'
        dotnet script UpdateSDKs/UpdateSDKs.csx -- "${{ github.event.inputs.platform }}" "${{ github.event.inputs.cobrowse_sdk_version }}"

    - name: Install .NET workloads
      run: |
        sudo dotnet workload restore

    - name: Restore NuGet packages
      run: |
        dotnet restore CobrowseIO.sln --source https://api.nuget.org/v3/index.json

    - name: Build SDK projects
      run: |
        dotnet build Android/NumbersJava.Android/NumbersJava.Android.csproj --configuration "Release" --no-dependencies --no-restore
        dotnet build Android/CborJava.Android/CborJava.Android.csproj --configuration "Release" --no-dependencies --no-restore
        dotnet build Android/CobrowseIO.Android/CobrowseIO.Android.csproj --configuration "Release" --no-dependencies --no-restore
        dotnet build iOS/CobrowseIO.iOS/CobrowseIO.iOS.csproj --configuration "Release" --no-dependencies --no-restore
        dotnet build SDK/CobrowseIO/CobrowseIO.csproj --configuration "Release" --no-dependencies --no-restore

    - name: Create NuGet packages
      run: |
        dotnet pack SDK/CobrowseIO/CobrowseIO.csproj /p:NuspecFile=../../CobrowseIO.DotNet.nuspec --no-build
    - name: Copy nupkg files to artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          SDK/CobrowseIO/bin/Release/CobrowseIO.DotNet.*.nupkg
        retention-days: 7
        if-no-files-found: error

    # If the SDK was updated, commit the changes back to the repo
    - name: Commit the changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        PLATFORM="${{ github.event.inputs.platform }}"
        PLATFORM=$(echo "$PLATFORM" | tr '[:upper:]' '[:lower:]')
        if [ "$PLATFORM" = "android" ]; then
          FILES_TO_COMMIT="cobrowse-sdk-android-binary Android/CobrowseIO.Android/CobrowseIO.Android.csproj"
          PROJECT_PATH="Android/CobrowseIO.Android/CobrowseIO.Android.csproj"
          PLATFORM_HUMANIZED="Android"
        elif [ "$PLATFORM" = "ios" ]; then
          FILES_TO_COMMIT="cobrowse-sdk-ios-binary iOS/CobrowseIO.iOS/CobrowseIO.iOS.csproj"
          PROJECT_PATH="iOS/CobrowseIO.iOS/CobrowseIO.iOS.csproj"
          PLATFORM_HUMANIZED="iOS"
        else
          echo "Unsupported platform: $PLATFORM"
          exit 1
        fi

        if [[ `git status --porcelain $FILES_TO_COMMIT` ]]; then
          # Commit as Github Actions Bot
          # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          COBROWSE_VERSION=$(xmllint --xpath 'string(/Project/PropertyGroup/Version)' Android/CobrowseIO.Android/CobrowseIO.Android.csproj)
          COBROWSE_VERSION=$(xmllint --xpath 'string(/Project/PropertyGroup/Version)' iOS/CobrowseIO.iOS/CobrowseIO.iOS.csproj)
          COBROWSE_VERSION=$(xmllint --xpath 'string(/Project/PropertyGroup/Version)' "$PROJECT_PATH")
          git add $FILES_TO_COMMIT
          git commit -m "feat: update Cobrowse ${PLATFORM_HUMANIZED} SDK to ${COBROWSE_VERSION}"
          # Pull the changes that might have been commited during this run
          git config pull.rebase true
          git config rebase.autoStash true
          git pull origin
          git push
        else
          echo "Native SDK hasn't been updated"
        fi        
